dist: trusty

language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install: 
        - mkdir -p /opt/maven
        - curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz%7Ctar -xz --strip 1 -C /opt/maven
        - export MAVEN_HOME=/opt/maven
        - export PATH=${MAVEN_HOME}/bin:${PATH}
install:
  - apt-get install oracle-java8-installer
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn -Psafer -B -e -T 1C verify
arch:
  - ppc64le
  - amd64
jdk:
  - openjdk8

